apiVersion: v1
kind: Service
metadata:
  name: dev-quote-api
  labels:
    app: dev-quote-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: dev-quote-api
